id: I0B4044B4
source: https://sakyaresearch.org
source_file: null
initial_creation_type: input
imported: '2022-06-19T10:18:05.977872'
last_modified: '2022-06-19T10:18:05.977885'
parser: null
source_metadata:
  title: Hagiography of Tshar chen Blo gsal rgya mtsho (1502–1566/67); Lamdre Lobshe,
    vol. kha, title no. 5
  author: ངག་དབང་བློ་བཟང་བརྒྱ་མཚོ།
  description: 'Digital version 2.0 {Tibetan}; master xml (completed: 2013-08-26);
    converted from external file, unrevised, thematic TEI markup'
  file_info:
  - 'Language: Tibetan'
  - 'Coverage: Full Text'
  - 'Accessible: publicly'
  responibilities:
  - Digital edition:ས་སྐྱ་ཞིབ་འཇུག་ཁང་། (src)
  - Text input:རྫོང་སར་ཁམས་བྱེའི་ལྔ་རིག་སློབ་གླིང་། སྡེ་དགེ་རྫོང་སར། (dzkj)
  - Editorial process:Mathias Fermer (mf), Kunga Dorje (kun)
  - TEI Encoding:ས་སྐྱ་ཞིབ་འཇུག་ཁང་།
  - TEI Markup:Mathias Fermer (mf)
  - Revisions/Corrections:-
  text_witnesses: https://sakyaresearch.org/sources/386
  bases:
    ae7c:
      title: Hagiography of Tshar chen Blo gsal rgya mtsho (1502–1566/67); Lamdre
        Lobshe, vol. kha, title no. 5
      order: 1
      base_file: ae7c.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
